spring.application.name=demo-rest

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html

# Чтобы Spring HATEOAS отдавал чистый HAL (application/hal+json -> application/json в браузере Swagger)
spring.hateoas.use-hal-as-default-json-media-type=true
